// provinceData.js
export const provinceData = [
  { name: "An Giang", code: "89" },
  { name: "Bà Rịa - Vũng Tàu", code: "77" },
  { name: "Bắc Giang", code: "24" },
  { name: "Bắc Kạn", code: "06" },
  { name: "Bạc Liêu", code: "95" },
  { name: "Bắc Ninh", code: "27" },
  { name: "Bến Tre", code: "83" },
  { name: "Bình Định", code: "52" },
  { name: "Bình Dương", code: "74" },
  { name: "Bình Phước", code: "70" },
  { name: "Bình Thuận", code: "60" },
  { name: "Cà Mau", code: "96" },
  { name: "Cần Thơ", code: "92" },
  { name: "Cao Bằng", code: "04" },
  { name: "Đà Nẵng", code: "48" },
  { name: "Đắk Lắk", code: "66" },
  { name: "Đắk Nông", code: "67" },
  { name: "Điện Biên", code: "11" },
  { name: "Đồng Nai", code: "75" },
  { name: "Đồng Tháp", code: "87" },
  { name: "Gia Lai", code: "64" },
  { name: "Hà Giang", code: "02" },
  { name: "Hà Nam", code: "35" },
  { name: "Hà Nội", code: "01" },
  { name: "Hà Tĩnh", code: "42" },
  { name: "Hải Dương", code: "30" },
  { name: "Hải Phòng", code: "31" },
  { name: "Hậu Giang", code: "93" },
  { name: "Hòa Bình", code: "17" },
  { name: "Hưng Yên", code: "33" },
  { name: "Khánh Hòa", code: "56" },
  { name: "Kiên Giang", code: "91" },
  { name: "Kon Tum", code: "62" },
  { name: "Lai Châu", code: "12" },
  { name: "Lâm Đồng", code: "68" },
  { name: "Lạng Sơn", code: "20" },
  { name: "Lào Cai", code: "10" },
  { name: "Long An", code: "80" },
  { name: "Nam Định", code: "36" },
  { name: "Nghệ An", code: "40" },
  { name: "Ninh Bình", code: "37" },
  { name: "Ninh Thuận", code: "58" },
  { name: "Phú Thọ", code: "25" },
  { name: "Phú Yên", code: "54" },
  { name: "Quảng Bình", code: "44" },
  { name: "Quảng Nam", code: "49" },
  { name: "Quảng Ngãi", code: "51" },
  { name: "Quảng Ninh", code: "22" },
  { name: "Quảng Trị", code: "45" },
  { name: "Sóc Trăng", code: "94" },
  { name: "Sơn La", code: "14" },
  { name: "Tây Ninh", code: "72" },
  { name: "Thái Bình", code: "34" },
  { name: "Thái Nguyên", code: "19" },
  { name: "Thanh Hóa", code: "38" },
  { name: "Thừa Thiên Huế", code: "46" },
  { name: "Tiền Giang", code: "82" },
  { name: "TP Hồ Chí Minh", code: "79" },
  { name: "Trà Vinh", code: "84" },
  { name: "Tuyên Quang", code: "08" },
  { name: "Vĩnh Long", code: "86" },
  { name: "Vĩnh Phúc", code: "26" },
  { name: "Yên Bái", code: "15" }
];

export const districtData = {
  "01": [ // Hà Nội
    { name: "Ba Đình", code: "001" },
    { name: "Hoàn Kiếm", code: "002" },
    { name: "Tây Hồ", code: "003" },
    { name: "Long Biên", code: "004" },
    { name: "Cầu Giấy", code: "005" },
    { name: "Đống Đa", code: "006" },
    { name: "Hai Bà Trưng", code: "007" },
    { name: "Hoàng Mai", code: "008" },
    { name: "Thanh Xuân", code: "009" },
    { name: "Bắc Từ Liêm", code: "021" },
    { name: "Nam Từ Liêm", code: "250" },
    { name: "Sóc Sơn", code: "016" },
    { name: "Đông Anh", code: "017" },
    { name: "Gia Lâm", code: "018" },
    { name: "Ba Vì", code: "019" },
    { name: "Chương Mỹ", code: "020" },
    { name: "Đan Phượng", code: "022" },
    { name: "Hoài Đức", code: "023" },
    { name: "Mê Linh", code: "246" },
    { name: "Mỹ Đức", code: "024" },
    { name: "Phú Xuyên", code: "025" },
    { name: "Phúc Thọ", code: "026" },
    { name: "Quốc Oai", code: "027" },
    { name: "Sơn Tây", code: "251" },
    { name: "Thạch Thất", code: "028" },
    { name: "Thanh Oai", code: "029" },
    { name: "Thường Tín", code: "030" },
    { name: "Ứng Hòa", code: "031" },
    { name: "Thanh Trì", code: "032" }
  ],
  "79": [ // TP Hồ Chí Minh
    { name: "Quận 1", code: "760" },
    { name: "Quận 3", code: "762" },
    { name: "Quận 4", code: "763" },
    { name: "Quận 5", code: "764" },
    { name: "Quận 6", code: "765" },
    { name: "Quận 7", code: "766" },
    { name: "Quận 8", code: "767" },
    { name: "Quận 10", code: "768" },
    { name: "Quận 11", code: "769" },
    { name: "Quận 12", code: "770" },
    { name: "Quận Bình Tân", code: "771" },
    { name: "Quận Bình Thạnh", code: "772" },
    { name: "Quận Gò Vấp", code: "773" },
    { name: "Quận Phú Nhuận", code: "774" },
    { name: "Quận Tân Bình", code: "775" },
    { name: "Quận Tân Phú", code: "776" },
    { name: "Thành phố Thủ Đức", code: "777" },
    { name: "Huyện Bình Chánh", code: "783" },
    { name: "Huyện Cần Giờ", code: "784" },
    { name: "Huyện Củ Chi", code: "785" },
    { name: "Huyện Hóc Môn", code: "786" },
    { name: "Huyện Nhà Bè", code: "787" }
  ],
  "48": [ // Đà Nẵng
    { name: "Hải Châu", code: "490" },
    { name: "Cẩm Lệ", code: "491" },
    { name: "Thanh Khê", code: "492" },
    { name: "Liên Chiểu", code: "493" },
    { name: "Ngũ Hành Sơn", code: "494" },
    { name: "Sơn Trà", code: "495" },
    { name: "Hòa Vang", code: "497" }
  ],
  "31": [ // Hải Phòng
    { name: "Hồng Bàng", code: "303" },
    { name: "Ngô Quyền", code: "304" },
    { name: "Lê Chân", code: "305" },
    { name: "Hải An", code: "306" },
    { name: "Kiến An", code: "307" },
    { name: "Đồ Sơn", code: "308" },
    { name: "Dương Kinh", code: "309" },
    { name: "Thuỷ Nguyên", code: "311" },
    { name: "An Dương", code: "312" },
    { name: "An Lão", code: "313" },
    { name: "Kiến Thuỵ", code: "314" },
    { name: "Tiên Lãng", code: "315" },
    { name: "Vĩnh Bảo", code: "316" },
    { name: "Cát Hải", code: "317" },
    { name: "Bạch Long Vĩ", code: "318" }
  ],
  "92": [ // Cần Thơ
    { name: "Ninh Kiều", code: "916" },
    { name: "Ô Môn", code: "917" },
    { name: "Bình Thuỷ", code: "918" },
    { name: "Cái Răng", code: "919" },
    { name: "Thốt Nốt", code: "923" },
    { name: "Vĩnh Thạnh", code: "924" },
    { name: "Cờ Đỏ", code: "925" },
    { name: "Phong Điền", code: "926" },
    { name: "Thới Lai", code: "927" }
  ]
  // Add more districts for other provinces as needed
  // This is a partial list - you would need to add districts for all provinces
};